# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 360)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_openfile = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lab_openfile.setObjectName("lab_openfile")
        self.horizontalLayout_2.addWidget(self.lab_openfile)
        self.btn_openfile = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_openfile.setObjectName("btn_openfile")
        self.horizontalLayout_2.addWidget(self.btn_openfile)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 261, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_time.setObjectName("lab_time")
        self.horizontalLayout.addWidget(self.lab_time)
        self.slider_time = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName("slider_time")
        self.horizontalLayout.addWidget(self.slider_time)
        self.lab_duration = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lab_duration.setObjectName("lab_duration")
        self.horizontalLayout.addWidget(self.lab_duration)
        self.btn_play = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 261, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lab_openfile.setText(_translate("Form", "No Music"))
        self.btn_openfile.setText(_translate("Form", "Open file"))
        self.lab_time.setText(_translate("Form", "00:00"))
        self.lab_duration.setText(_translate("Form", "00:00"))
        self.btn_play.setText(_translate("Form", "Play"))
